
#alignment method
align_method: "SIFT"
align_use_n_feats: true
align_feats: 500
align_use_treshold: false
align_threshold: 0.5
erase_bottom: false

#comparison method
compare_method: "spline"
estimate_uncertainty: true

#output
publish_alignment: true
save_alignment: false
save_alignment_folder: "./"
publish_comparison: true
save_comparison: false
save_comparison_location: ""
